-- =====================================================
-- Trading System Database Schema
-- Created for MVP 2: Data Acquisition Module
-- =====================================================

-- Create kline table for storing K-line data from Binance
CREATE TABLE IF NOT EXISTS kline (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp BIGINT NOT NULL,
    open DOUBLE PRECISION NOT NULL,
    high DOUBLE PRECISION NOT NULL,
    low DOUBLE PRECISION NOT NULL,
    close DOUBLE PRECISION NOT NULL,
    volume DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for efficient querying by symbol and timestamp
CREATE INDEX IF NOT EXISTS idx_kline_symbol_timestamp ON kline(symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_kline_timestamp ON kline(timestamp DESC);

-- Create trade table for storing executed trades (for future MVPs)
CREATE TABLE IF NOT EXISTS trade (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp BIGINT NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    type VARCHAR(10) NOT NULL, -- BUY/SELL
    status VARCHAR(20) NOT NULL, -- PENDING/COMPLETED/CANCELLED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for trade queries
CREATE INDEX IF NOT EXISTS idx_trade_symbol_timestamp ON trade(symbol, timestamp DESC);

-- Create signal table for storing trading signals (for future MVPs)
CREATE TABLE IF NOT EXISTS signal (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp BIGINT NOT NULL,
    type VARCHAR(10) NOT NULL, -- BUY/SELL
    strength DOUBLE PRECISION, -- Signal strength (0-1)
    source VARCHAR(50), -- TA/AI
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for signal queries
CREATE INDEX IF NOT EXISTS idx_signal_symbol_timestamp ON signal(symbol, timestamp DESC);

-- Create health_check table for system monitoring
CREATE TABLE IF NOT EXISTS health_check (
    id SERIAL PRIMARY KEY,
    status VARCHAR(50) NOT NULL,
    message TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for health check queries
CREATE INDEX IF NOT EXISTS idx_health_check_timestamp ON health_check(timestamp DESC);

-- =====================================================
-- Sample Data Insertion (for testing)
-- =====================================================

-- Insert sample health check record
INSERT INTO health_check (status, message) VALUES ('UP', 'System initialized successfully');

-- =====================================================
-- Database Statistics and Maintenance
-- =====================================================

-- Analyze tables for query optimization
ANALYZE kline;
ANALYZE trade;
ANALYZE signal;
ANALYZE health_check;

-- =====================================================
-- Comments and Documentation
-- =====================================================

COMMENT ON TABLE kline IS 'Stores K-line (candlestick) data from cryptocurrency exchanges';
COMMENT ON COLUMN kline.symbol IS 'Trading pair symbol (e.g., BTCUSDT)';
COMMENT ON COLUMN kline.timestamp IS 'Unix timestamp in milliseconds';
COMMENT ON COLUMN kline.open IS 'Opening price for the time period';
COMMENT ON COLUMN kline.high IS 'Highest price during the time period';
COMMENT ON COLUMN kline.low IS 'Lowest price during the time period';
COMMENT ON COLUMN kline.close IS 'Closing price for the time period';
COMMENT ON COLUMN kline.volume IS 'Trading volume for the time period';

COMMENT ON TABLE trade IS 'Stores executed trades for portfolio tracking';
COMMENT ON COLUMN trade.type IS 'Trade type: BUY or SELL';
COMMENT ON COLUMN trade.status IS 'Trade status: PENDING, COMPLETED, or CANCELLED';

COMMENT ON TABLE signal IS 'Stores trading signals generated by TA or AI algorithms';
COMMENT ON COLUMN signal.type IS 'Signal type: BUY or SELL';
COMMENT ON COLUMN signal.strength IS 'Signal strength from 0 to 1';
COMMENT ON COLUMN signal.source IS 'Signal source: TA (Technical Analysis) or AI';

COMMENT ON TABLE health_check IS 'Stores system health check records for monitoring'; 